sudo: required
services:
  - docker
dist: trusty
language: cpp
compiler:
  - gcc
  
addons:
  apt:
    sources:
     - ubuntu-toolchain-r-test
     - ubuntu-trusty
    packages:
     - qt5-default
     - debhelper
     - gcc-5
     - g++-5
    alternatives:
     - alternative:
       name: gcc
       link: /usr/bin/gcc
       path: /usr/bin/gcc-5
       priority: 50
     - alternative:
       name: g++
       link: /usr/bin/g++
       path: /usr/bin/g++-5
       priority: 50

env:
 - COMPILER=g++-5
 - CXX=g++-5
 - CC=gcc-5



script:
  - gcc --version && g++ --version
  - dpkg-buildpackage -rfakeroot
