sudo: required
#services:
#  - docker
dist: trusty
language: cpp
compiler:
  - gcc-5
  
addons:
  apt:
    sources:
     - ubuntu-toolchain-r-test
     - ubuntu-trusty
    packages:
     - debhelper
     - gcc-5
     - g++-5
     - pdebuilder

#env:
before_script:
  - export COMPONENTS="main contrib non-free"
  - export BASETGZ="./xenial-amd64-base.tgz"
  - export BUILDRESULT="./debs"
  - export MIRRORSITE="http://archive.ubuntu.com/ubuntu/"
  - export COMPONENTS="main restricted universe multiverse"
  
before_install:
  - sudo add-apt-repository --yes ppa:beineri/opt-qt551-trusty
  - sudo apt-get update -qq

install:
  - sudo apt-get -y install qt55[QTPACKAGE]

script:
 - sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-5 100
 - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-5 100
 - source /opt/qt55/bin/qt55-env.sh
 - wget http://pdebuild.bagrintsev.me/images/xenial-amd64-base.tgz -O /tmp/xenial-amd64-base.tgz
 - sudo DIST="xenial" ARCH="amd64" BASETGZ="/tmp/xenial-amd64-base.tgz" pdebuild
 #- dpkg-buildpackage -rfakeroot -d
