sudo: required
services:
  - docker
dist: trusty
language: cpp
compiler:
  - gcc
  
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    - ubuntu-trusty
    packages:
    - qt5-default
    - debhelper
    - gcc-5
    - g++-5

install:
 - if [ "$CXX" = "g++" ]; then sudo apt-get install -qq g++-5; fi
 - if [ "$CXX" = "g++" ]; then export CXX="g++-5"; fi

script:
  - dpkg-buildpackage -rfakeroot
