dist: xenial
language: cpp
compiler:
  - gcc

before_install:
- sudo add-apt-repository --yes ppa:ubuntu-sdk-team/ppa
- sudo apt-get update -qq
- sudo apt-get install ubuntu-sdk qt5-default qttools5-dev-tools qtbase5-dev qtbase5-private-dev libqt5xmlpatterns5 libqt5xmlpatterns5-dev libqt5xml5
#- wget http://download.qt.io/archive/qt/5.4/5.4.1/single/qt-everywhere-opensource-src-5.4.1.tar.gz -O /tmp/qt.tar.gz
#- tar -xpf /tmp/qt.tar.gz
#- cd qt-everywhere-opensource-src-5.4.1 && ./configure -opensource -confirm-license -qt-xcb && make && sudo make install
#- cd ../..
- wget http://download.qt.io/archive/qt/5.4/5.4.1/submodules/qtx11extras-opensource-src-5.4.1.tar.gz -O /tmp/qx11extras.tar.gz
- tar -xvpf /tmp/qx11extras.tar.gz
- cd qtx11extras-opensource-src-5.4.1 && qmake && make && sudo make install
- cd ..

script:
  - qmake -project
  - qmake qsc.pro
  - make
