sudo: required
services:
  - docker
dist: trusty
language: cpp
compiler:
  - gcc
  
addons:
apt:
  packages:
  - qt5-default

before_install:
- sudo apt-get update -qq
- sudo apt-get install -qq qt5-qmake qtbase5-dev dpkg-dev

script:
  - dpkg-buildpackage -rfakeroot
