sudo: required
services:
  - docker
dist: trusty
language: cpp
compiler:
  - gcc
  
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    - ubuntu-trusty
    packages:
    - qt5-default
    - debhelper
    - gcc-5
    - g++-5

script:
  - export CXX="g++-5" CC="gcc-5"
  - dpkg-buildpackage -rfakeroot
