sudo: required
services:
  - docker
dist: trusty
language: cpp
compiler:
  - gcc
  
addons:
  apt:
    sources:
    - george-edison55-precise-backports
    - debian-sid
    packages:
    - qt5-default
    - debhelper

script:
  - dpkg-buildpackage -rfakeroot
