sudo: required
services:
  - docker
dist: trusty
language: cpp
compiler:
  - gcc
  
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    - ubuntu-trusty
    packages:
    - qt5-default
    - debhelper
    - gcc-5
    - g++-5

script:
  - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-5 90
  - dpkg-buildpackage -rfakeroot
