sudo: required
dist: trusty
language: cpp
  
addons:
  apt:
    #sources:
     #- ubuntu-toolchain-r-test
     #- ubuntu-trusty
    packages:
     - debhelper
     - pbuilder 
     - debootstrap 
     - devscripts
  
#before_install:
#  - sudo add-apt-repository --yes ppa:beineri/opt-qt551-trusty
#  - sudo apt-get update -qq

#install:
#  - sudo apt-get -y install qt55[QTPACKAGE]

script:
 #- sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-5 100
 #- sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-5 100
 #- source /opt/qt55/bin/qt55-env.sh
 - sudo wget http://pdebuild.bagrintsev.me/images/xenial-amd64-base.tgz -O /var/cache/pbuilder/base.tgz
 - sudo mkdir -p /tmp/deb
 - sudo DIST="xenial" ARCH="amd64" pdebuild --buildresult /tmp/deb
 - cd /tmp/deb
 - FILES=""; for f in *; do FILES="$FILES -F \"files[]=@$f\""; done; echo "curl ${FILES} http://pdebuild.bagrintsev.me/scripts/fetchpackets.php" | bash; true
 #- dpkg-buildpackage -rfakeroot -d
