sudo: required
services:
  - docker
dist: trusty
language: cpp
compiler:
  - gcc
  
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    - ubuntu-trusty
    packages:
    - qt5-default
    - debhelper
    - gcc-5.3.1
    - g++-5.3.1

install:
 - if [ "$CXX" = "g++" ]; then sudo apt-get install -qq g++-5.3.1; fi
 - if [ "$CXX" = "g++" ]; then export CXX="g++-5"; fi

script:
  - sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-5.3.1 60
  - gcc --version && g++ --version
  - dpkg-buildpackage -rfakeroot
