sudo: required
#services:
#  - docker
dist: trusty
language: cpp
compiler:
  - gcc-5
  
addons:
  apt:
    sources:
     - ubuntu-toolchain-r-test
     - ubuntu-trusty
    packages:
     #- qt5-default
     #- qtbase5-dev
     - debhelper
     - gcc-5
     - g++-5
    alternatives:
     - alternative:
       name: gcc
       link: /usr/bin/gcc
       path: /usr/bin/gcc-5
       priority: 100
     - alternative:
       name: g++
       link: /usr/bin/g++
       path: /usr/bin/g++-5
       priority: 100
       
before_install:
  - sudo add-apt-repository --yes ppa:beineri/opt-qt554-trusty
  - sudo apt-get update -qq

install:
  - sudo apt-get -y install qt54tools qt54svg qt54webkit qt54script qt54base

script:
  - sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-5 100
  - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-5 100
  - dpkg-buildpackage -rfakeroot
