Document: ramblerpcutility
Title: Debian ramblerpcutility Manual
Author: <insert document author here>
Abstract: This manual describes what ramblerpcutility is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/ramblerpcutility/ramblerpcutility.sgml.gz

Format: postscript
Files: /usr/share/doc/ramblerpcutility/ramblerpcutility.ps.gz

Format: text
Files: /usr/share/doc/ramblerpcutility/ramblerpcutility.text.gz

Format: HTML
Index: /usr/share/doc/ramblerpcutility/html/index.html
Files: /usr/share/doc/ramblerpcutility/html/*.html
